# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  #random utilities
  - name: utils
    before: |
      sudo apt-get install tree
  #https://learn.microsoft.com/en-us/powershell/scripting/install/install-debian?view=powershell-7.4
  - name: powershell
    before: |
      sudo apt-get update
      sudo apt-get install -y wget
      source /etc/os-release
      wget -q https://packages.microsoft.com/config/debian/$VERSION_ID/packages-microsoft-prod.deb
      find / -name packages-microsoft-prod.deb -print
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
    # init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    # command: echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

# sudo dpkg -i packages-microsoft-prod.deb
# rm packages-microsoft-prod.deb
# sudo apt-get update
# sudo apt-get install -y powershell