AWSTemplateFormatVersion: 2010-09-09
Description: Create a role for users to assume when using sts
Parameters:
  BucketName: 
    Type: String
    Default: "sts-fun-clds"
Resources:
  MyStsRole: 
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: arn:aws:iam::647264525674:user/sts-machine-user
              #Service:
              #  - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: 
                  - "arn:aws:s3:::*"
                  - !Sub "arn:aws:s3:::${BucketName}"
                  - !Sub "arn:aws:s3:::${BucketName}/*"
  MyStsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName