#!/usr/bin/env bash

#check for bucket name
if [ -z "$1" ]; then
    echo -e "A bucket name should be provided\neg: ./create_bucket bucket-name"
    # exit 1 this causes terminal to close
fi

#https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html

aws s3api create-bucket \
--bucket $1 \
--region ap-south-1 \
--create-bucket-configuration LocationConstraint=ap-south-1 \
--query Location \
--output text

#can fine tune the output like this,
# {
#     "Location": "http://my-new-silver-bucket-clds.s3.amazonaws.com/"
# }
#with --query and --output