AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyServerlessApp:
    Type: AWS::Serverless::Function
    Properties:
    ## hanlder, runtime already handled through Dockerfile
      # Handler: function.lambda_handler
      # Runtime: python3.12
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile          
      DockerContext: .              

