#!/usr/bin/env bash

echo "== deploy cfn template"

STACK_NAME="cfn-s3-simple-again"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-west-1 \
--stack-name $STACK_NAME